version: '3'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: mssql_container
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourPassword123!
